config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Generic syntax:
  # verb "path", to: "controller#action"
  get "/about_us", to: "pages#about_us"
  get "/contacts", to: "pages#contacts"
  get "/home", to: "pages#home", as: :homepage

  get "/restaurants", to: "pages#restaurants"

  # get "/contacts", to: "pages#contacts"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about_us

  end

  def contacts


  end

  def home

  end

  def restaurants

    # TOMORROW
    # @restaurants = Restaurant.all

    @restaurants = ["felice a testaccio", "tagliato", "charlotte"]
    p "forza milan"
    if params["restaurant"]
      @restaurants = @restaurants.select {|rest| rest.start_with?(params["restaurant"])}
    end
  end
end



# restaurants = ["felice a testaccio", "tagliato", "charlotte"]

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p>this is a fake navbar</p>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<p>forza milan</p>

app/views/pages/contacts.html.erb
<h1>contacts page</h1>

<p>get in touch with us</p>


<form action="/contacts" method="get">
  <input type="text" name="member2" placeholder="Who are you looking for?">
  <input type="submit">
</form>

app/views/pages/home.html.erb
<p>this is the home</p>
<p>Now is <%= Time.now %></p>


<%= link_to "go to restaurants list", about_us_path %>

<%= link_to "GOHOME", homepage_path, class: "frank" %>
<%#= <a href="/about_us">go to restaurants list</a> %>

app/views/pages/restaurants.html.erb
<h1>here's my list of restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant %></li>
  <% end %>
</ul>


<form action="/restaurants" method="get">
  <input type="text" name="restaurant" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<form action="/restaurants" method="post">
  <input type="text" name="restaurant" placeholder="Who are you looking for?">
  <input type="submit">
</form>


<a href="/restaurants?restaurant=t">restaurants that start with "T"</a>